config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :next_travels
  resources :travels
  resources :profiles
  resources :profiles
  resources :comments
  devise_for :models
  resources :posts
  devise_for :users
  
  get 'homepage', to: 'home#index'
  get 'list', to: 'posts#list'
  get 'body', to: 'posts#body'
  get 'search', to: 'search#index'
  get 'user_profile', to: 'users#user_profile'
  get 'maps',to: 'maps#index'
  get 'analytics',to: 'travels#analytics'
  get 'dates',to: 'travels#date'

  
  
  get 'photosOf',to: 'photos#photosOf'
  get 'photoDestroy',to: 'photos#destroy'
  

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'home#index'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :body, presence: true

	ratyrate_rateable "body"

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/next_travel.rb
class NextTravel < ActiveRecord::Base

	validates :location,:date,presence: true

	


	belongs_to :user

	geocoded_by :location
	after_validation :geocode
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :user
	validates :image, presence: true
	validates :description, presence: true
	validates :location, presence: true
	
	has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	
	has_many :comments, dependent: :destroy
	

	validates :titolo, presence: true, allow_blank: false,length: { maximum: 30 }
	validates :description, presence: true, allow_blank: false,length: { maximum: 80 }
	validates :location, presence: true, allow_blank: false,length: { maximum: 30, minimum: 2 }
	validates :body, presence: true, allow_blank: false
	
	ratyrate_rateable "body"

end

app/models/profile.rb
 class Profile < ActiveRecord::Base

	belongs_to :user
	validates :user_id, :username, uniqueness: true, presence: true


	
	
	#Gemma paperclip attachment foto profilo 
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/travel.rb
class Travel < ActiveRecord::Base


	validates :location,:date,presence: true

	

	belongs_to :user

	geocoded_by :location
	after_validation :geocode


	protected

	def ensure_user_not_has_duplicates
		if Travel.exists?

		end	

	end	



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :database_authenticatable, :confirmable


  has_many :posts, dependent: :destroy
  has_many :photos, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  has_many :travels, dependent: :destroy
  has_many :nextTravels, dependent: :destroy

  acts_as_messageable

  ratyrate_rater

  # in User.rb
  protected
  def confirmation_required?
    false
  end
 
  def mailboxer_name
    self.id
  end
 
  def mailboxer_email(object)
    self.email
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end


  # GET /comments/new
  def new
    @comment = Comment.new
    
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    @comment.user_id = current_user.id
    
    

      

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :controller => :users,:action=>:user_profile, :id=>@comment.post.user.id, :post_id=>@comment.post_id }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to :controller => :users,:action=>:user_profile, :id=>@comment.post.user.id, :post_id=>@comment.post_id }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :controller => :users,:action=>:user_profile, :id=>@comment.post.user.id, :post_id=>@comment.post_id }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
    	# how to get the number of unread messages for the current user
    	# using mailboxer
    	mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
	
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/travels_helper.rb
module TravelsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Assegno ad ogni commento l'id del post a cui appartiene -->
  <%= f.hidden_field :post_id, value: params[:post_id].to_i %>

  <div class="field">
    <%= f.text_area :body , class: "form-control"%>
  </div>
    <div class="actions">
    <%= f.submit "Create Comment",class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_list.html.erb
<% @comments.order("created_at DESC").limit(20).each do |c| %>

	<%= rating_for c, "body" %>
	
	<p><i><b>

	<% if !(c.user.profile == nil) %>
		<%= link_to c.user.profile.username , user_profile_path(id: c.user.id,post_id: last_post_of(c.user.id))%>

	<% else %>
		<%= link_to c.user.email , user_profile_path(id: c.user.id,post_id: last_post_of(c.user.id))%>
	<% end %>	

	</i></b>says: </p>

	<p>	
		
		<%= c.body %>
		
	
		<br>
		<i>on <%= c.created_at %></i>
		<% if (c.user.id == current_user.id || params[:id].to_i==current_user.id) %>
			<%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true" style="position: relative; left:300px;"></span>'.html_safe, c, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>

	</p>




	<hr>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.parent_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>