config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :next_travels
  resources :travels
  resources :profiles
  resources :profiles
  resources :comments
  devise_for :models
  resources :posts
  devise_for :users
  
  get 'homepage', to: 'home#index'
  get 'list', to: 'posts#list'
  get 'body', to: 'posts#body'
  get 'search', to: 'search#index'
  get 'user_profile', to: 'users#user_profile'
  get 'maps',to: 'maps#index'
  get 'analytics',to: 'travels#analytics'
  get 'dates',to: 'travels#date'

  
  
  get 'photosOf',to: 'photos#photosOf'
  get 'photoDestroy',to: 'photos#destroy'
  

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'home#index'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :body, presence: true

	ratyrate_rateable "body"

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/next_travel.rb
class NextTravel < ActiveRecord::Base

	validates :location,:date,presence: true

	


	belongs_to :user

	geocoded_by :location
	after_validation :geocode
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :user
	validates :image, presence: true
	validates :description, presence: true
	validates :location, presence: true
	
	has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	
	has_many :comments, dependent: :destroy
	

	validates :titolo, presence: true, allow_blank: false,length: { maximum: 30 }
	validates :description, presence: true, allow_blank: false,length: { maximum: 80 }
	validates :location, presence: true, allow_blank: false,length: { maximum: 30, minimum: 2 }
	validates :body, presence: true, allow_blank: false
	
	ratyrate_rateable "body"

end

app/models/profile.rb
 class Profile < ActiveRecord::Base

	belongs_to :user
	validates :user_id, :username, uniqueness: true, presence: true


	
	
	#Gemma paperclip attachment foto profilo 
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/travel.rb
class Travel < ActiveRecord::Base


	validates :location,:date,presence: true

	

	belongs_to :user

	geocoded_by :location
	after_validation :geocode


	protected

	def ensure_user_not_has_duplicates
		if Travel.exists?

		end	

	end	



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :database_authenticatable, :confirmable


  has_many :posts, dependent: :destroy
  has_many :photos, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  has_many :travels, dependent: :destroy
  has_many :nextTravels, dependent: :destroy

  acts_as_messageable

  ratyrate_rater

  # in User.rb
  protected
  def confirmation_required?
    false
  end
 
  def mailboxer_name
    self.id
  end
 
  def mailboxer_email(object)
    self.email
  end


end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
 
  	def new
      
  	end

  	def create
    	recipient = User.find_by_id(conversation_params[:recipient])
    	conversation = current_user.send_message(recipient, conversation_params[:body], conversation_params[:subject]).conversation
    	flash[:success] = "Your message was successfully sent!"
    	redirect_to conversation_path(conversation)
  	end
 	
  	def show
    	@receipts = conversation.receipts_for(current_user)
    	# mark conversation as read
    	conversation.mark_as_read(current_user)
  	end
 
 	def reply
    	current_user.reply_to_conversation(conversation, message_params[:body])
    	flash[:notice] = "Your reply message was successfully sent!"
    	redirect_to conversation_path(conversation)
  	end

  	def trash
    	conversation.move_to_trash(current_user)
    	redirect_to mailbox_inbox_path
  	end
 
  	def untrash
    	conversation.untrash(current_user)
    	redirect_to mailbox_inbox_path
  	end
 
  	private
    
    def message_params
      params.require(:message).permit(:body, :subject)
    end

 
  	def conversation_params
    	params.require(:conversation).permit(:subject, :body,:recipient)
  	end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
    	# how to get the number of unread messages for the current user
    	# using mailboxer
    	mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/travels_helper.rb
module TravelsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    
      
      <%= link_to image_tag(conversation.originator.profile.avatar.url, size: "64x64", class: "img-circle").html_safe , user_profile_path(id: conversation.originator.id,post_id: last_post_of(conversation.originator.id)) %>
    
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.profile.username %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>To: </b><%= conversation.participants[0].profile.username%></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <!--<%= truncate conversation.messages.last.body, length: 145 %>-->
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>

    

    <div >
      <% f.label :recipients %>
      <%= f.select(:recipient, User.where(id: params[:id]).collect {|p| [ p.email, p.id ] }, {}, { multiple: false , class: "form-control" })%>
    </div>
    <div >
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div >
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>
 
    <%= f.submit "Send Message", class: "btn btn-success" %>
 
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <%= link_to image_tag(message.sender.profile.avatar.url, size: "64x64", class: "img-circle").html_safe , user_profile_path(id: message.sender.id,post_id: last_post_of(message.sender.id)) %>      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.profile.username %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <div class="spacer"></div>
    <div class="col-md-6 text-right">
  </div>

  </div>
 
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>
 
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div >
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>

        <!-- Trash button -->


    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger',  method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>

        <div class="clearfix"></div>
      </div>
    </div>
  </div>
 
</div>