config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :next_travels
  resources :travels
  resources :profiles
  resources :profiles
  resources :comments
  devise_for :models
  resources :posts
  devise_for :users
  
  get 'homepage', to: 'home#index'
  get 'list', to: 'posts#list'
  get 'body', to: 'posts#body'
  get 'search', to: 'search#index'
  get 'user_profile', to: 'users#user_profile'
  get 'maps',to: 'maps#index'
  get 'analytics',to: 'travels#analytics'
  get 'dates',to: 'travels#date'

  
  
  get 'photosOf',to: 'photos#photosOf'
  get 'photoDestroy',to: 'photos#destroy'
  

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :database_authenticatable, :confirmable


  has_many :posts, dependent: :destroy
  has_many :photos, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  has_many :travels, dependent: :destroy
  has_many :nextTravels, dependent: :destroy

  acts_as_messageable

  ratyrate_rater

  # in User.rb
  protected
  def confirmation_required?
    false
  end
 
  def mailboxer_name
    self.id
  end
 
  def mailboxer_email(object)
    self.email
  end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  def user_profile

  end  




end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def user_profile


		@post = Post.new
		@comment = Comment.new
		@photo = Photo.new
		
		
		

		if(params[:id].present?)
			@user = User.where(id: params[:id].to_i).first
			@posts = Post.where(user_id: params[:id]).order(created_at: :desc).limit(5)
			@travels = Travel.where(user_id: params[:id])
			@next_travels = NextTravel.where(user_id: params[:id])
			@photos = Photo.where(user_id: params[:id].to_i).order("created_at DESC")
			@post_count = Post.where(user_id: params[:id]).count
			@comments = Comment.where(post_id: params[:post_id].to_i)
		end
			
		if(params[:post_id].present? && params[:id].present?)
			@post_for_body = Post.where(user_id:params[:id],id: params[:post_id])
		end	


	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_infoTravels.html.erb
<!-- Informazioni Viaggi -->   


         <!-- Travels -->

         <% if !@travels.empty? %>
            <hr>
            <i><b>My travels..</b></i><br>  
            <% @travels.each do |travel| %>
               <ul>
                  <%=travel.location+", "+travel.date.to_s%>
                  <% if params[:id].to_i==current_user.id %>
                     <%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'.html_safe, travel, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>  
               </ul>
            <% end %>

         <% end %>
         
         <br>

         <% if params[:id].to_i==current_user.id %>
            <%= link_to "Aggiorna informazioni sui tuoi viaggi .." , :controller=>:travels,:action=>:new%>
         <% end %>

         <!-- Next Travels -->
                
         <% if !@next_travels.empty? %>
            <hr>
            <i><b>My next travels..</b></i><br>
            <% @next_travels.each do |ntravel| %>
               <ul>
                  <%=ntravel.location+", "+ntravel.date.to_s%>
                  <% if params[:id].to_i==current_user.id %>
                     <%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'.html_safe, ntravel, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>  
               </ul>
            <% end %>

         <% end %>
         
         <br>

         <% if params[:id].to_i==current_user.id %>
            <%= link_to "Aggiorna informazioni sui tuoi viaggi futuri.." , :controller=>:next_travels,:action=>:new%>
         <% end %>

app/views/users/_profileArticleLists.html.erb
<div class="profile-article_lists-wrapper" id="list_wrapper">

<% if !@posts.blank? %>

    <i>Last posts from <b><%= @user.profile.username %></b>:</i>
    <% @posts.each do |post| %>
        <% if (post.id==params[:post_id].to_i) %>
            <div class="panel-body" id="panel-body-selected" style="color:green;background-color:#E3FFE3;">
        <% else %>
            <div class="panel-body" id="panel-body">
        <% end %>
            
                <i><%= post.created_at %></i>
                <br>
                <b><%= link_to post.titolo,user_profile_path(id: post.user.id,post_id:post.id), data: { no_turbolink: true }%><b>
                <br>
                <i><%= post.description %></i>
                  
        </div>
    <% end %>
    <br>
    <p align ="center">
        <%= link_to "Show More Posts from "+@user.profile.username, posts_path(id: params[:id].to_i)%>
    </p>

<% end %>    

</div>

app/views/users/_profileInfo.html.erb
<div class="profile-info-wrapper">
   <% utente = @user %>
      <% if (utente.profile != nil) %>

         <!-- Se l'utente ha un profilo stampa informazioni profilo -->

         <!-- Info Profilo -->
         
         <b><%= utente.profile.nome+" "+utente.profile.cognome %></b><br>
         <i>a.k.a</i> <b><%= utente.profile.username%> </b>


         <!-- Settings Profilo se l'utente loggato è il proprietario del profilo -->
         

         <% if (params[:id].to_i==current_user.id && utente.profile!=nil)%>
                  
            <%= link_to '<span class="glyphicon glyphicon-wrench"></span> '.html_safe, edit_profile_path(utente.profile)%>
                  
         <% end %>

         <!-- Se l'utente ha un avatar stampalo altrimenti stampa l'immagine di default  -->
                  
         <% if (utente.profile.avatar.exists?) %>
         
            <%= image_tag(utente.profile.avatar.url, size: "160x100", class: "img-thumbnail") %>
         
         <% else %>


         
            <%= image_tag(image_path("avatar_notfound_light.png"), size: "160x100", class: "img-thumbnail") %>
               
         <% end %>  

         


         <br><br>

         <!-- Info Profilo  -->
         
         <% if !(utente.profile.luogo_nascita.empty?) %>
            Nato a: <%= utente.profile.luogo_nascita %><br>
         <% end %>
               
         <% if (utente.profile.data_nascita!=nil) %>
            Data Nascita: <%= utente.profile.data_nascita%><br>
         <% end %>

         <% if !(utente.profile.citta_attuale.empty?) %>
            Vive a: <%= utente.profile.citta_attuale%> <br>
         <% end %> 

         <% if (@post_count>0) %>
            Ha scritto <b><%= @post_count %></b> posts<br>
         <% end %>

         Registrato il: <br>
         <%=utente.created_at%>

         <br><br>

         <!-- START MENU -->

         <ol class="breadcrumb">

            <% if (@travels!=nil || @next_travels!=nil) %>
               <li>
                  <%= link_to '<span class="glyphicon glyphicon-map-marker"></span>'.html_safe , maps_path(id: utente.id), data: { no_turbolink: true } %>
               </li>
            <% end %>
                     
            <li>
               <%= link_to "<span class='glyphicon glyphicon-camera'></span>".html_safe, photos_path(id: params[:id].to_i) %>
                  
            <% if current_user.id == params[:id].to_i %>

               <li><span class="glyphicon glyphicon-pencil" id="pencil"></span></li>
                
            <% else %>
                  
               <li>
                  <%= link_to '<span class="glyphicon glyphicon-envelope" ></span> '.html_safe, new_conversation_path(id:params[:id]) %>
               </li>

            <% end %>

         </ol>

         <!-- END MENU -->
                
         <hr>

         <!-- Info Profilo -->

         <i><b>About me..</b></i> <br>
         <%= utente.profile.biografia%>
                



         <!-- Informazioni Viaggi 
          render partial: "infoTravels" 
         -->
                
         <hr>
                

      <% else %>

         <!-- Se l'utente non ha un profilo: -->

         <% if (params[:id].to_i==current_user.id) %>
            <p><%= link_to "Aggiorna Informazioni Profilo" , :controller => :profiles, :action => :new %></p>
         <% end %>
         
         <b><%= utente.email %></b><br>
         <% if (@post_count>0) %>
            Ha scritto <b><%= @post_count %></b> posts<br>
         <% end %>
         Registrato il: <i><%=utente.created_at%>
         <br>

              
      <% end %>

              

                     	

      <br>
   </div>


<!--
   Script che mi permette, durante la visualizzazione di un post, di visualizzare
   il form per inserire un nuovo post
-->

<script>
   $(document).ready(function(){

      $("#pencil").click(function(){
         $(".profile-body-wrapper").hide();
         $(".photos-wrapper").hide();
         $("#form-container").show();
         $("#panel-body-selected").css("background-color","white");
         $("#panel-body-selected").css("color","black");
      });


  

   });
</script>

app/views/users/_profilePosts.html.erb
<div class="profile-posts-wrapper">


   <!-- POST FORM  -->

   

   

   <% if((!params[:post_id].present? && params[:id].present? && params[:id].to_i==current_user.id)) %>  

      <div class="form-container-profile" id="form-container" >

   <% else %> 
      
      <div class="form-container-profile" id="form-container" hidden>

   <% end %>

         <%= render "posts/form"%>

      </div>




   <!-- SHOW POST -->
   <% if((params[:post_id].present? && params[:id].present?)) %>
      <div class="profile-body-wrapper">
      
         <% @post_for_body.each do |post| %>
            <h3><%= post.titolo %></h3>
            <% if (current_user.id == post.user_id) %>
               <%= link_to '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>'.html_safe, edit_post_path(post) %>
               <%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>   
            <!-- RATING -->
            <%= rating_for post, "body" %>
            <br>
            <i>
               <%= post.description %><br>
               <%= post.created_at %>
            </i><hr>
            
            <%= post.body %>


            <hr>

            

            <!-- Form inserimento commenti -->
            <%= render "comments/form"%>
            <!-- Lista commenti -->
            <%= render "comments/list"%>

         <% end %>
      </div>

   

      

   <% end %>


   

  

   





</div>

app/views/users/user_profile.html.erb
<% if user_signed_in? %>

   <!-- Dynamic Title (vedi full_title nell'application helper) -->
   <%= provide(:title,User.find_by_id(params[:id]).profile.username)%>

   


   
   <!-- LEFT SIDE-->
   <%= render partial: "users/profileInfo" %>



   <!-- CENTER -->
   <%= render partial: "users/profilePosts" %> 
   


   <!-- RIGH SIDE -->
   <%= render partial: "users/profileArticleLists" %>



<% else %>

   <strong>Must be logged in.</strong>

<% end %>


    