config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :next_travels
  resources :travels
  resources :profiles
  resources :profiles
  resources :comments
  devise_for :models
  resources :posts
  devise_for :users
  
  get 'homepage', to: 'home#index'
  get 'list', to: 'posts#list'
  get 'body', to: 'posts#body'
  get 'search', to: 'search#index'
  get 'user_profile', to: 'users#user_profile'
  get 'maps',to: 'maps#index'
  get 'analytics',to: 'travels#analytics'
  get 'dates',to: 'travels#date'

  
  
  get 'photosOf',to: 'photos#photosOf'
  get 'photoDestroy',to: 'photos#destroy'
  

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'home#index'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :body, presence: true

	ratyrate_rateable "body"

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/next_travel.rb
class NextTravel < ActiveRecord::Base

	validates :location,:date,presence: true

	


	belongs_to :user

	geocoded_by :location
	after_validation :geocode
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :user
	validates :image, presence: true
	validates :description, presence: true
	validates :location, presence: true
	
	has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	
	has_many :comments, dependent: :destroy
	

	validates :titolo, presence: true, allow_blank: false,length: { maximum: 30 }
	validates :description, presence: true, allow_blank: false,length: { maximum: 80 }
	validates :location, presence: true, allow_blank: false,length: { maximum: 30, minimum: 2 }
	validates :body, presence: true, allow_blank: false
	
	ratyrate_rateable "body"

end

app/models/profile.rb
 class Profile < ActiveRecord::Base

	belongs_to :user
	validates :user_id, :username, uniqueness: true, presence: true


	
	
	#Gemma paperclip attachment foto profilo 
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/travel.rb
class Travel < ActiveRecord::Base


	validates :location,:date,presence: true

	

	belongs_to :user

	geocoded_by :location
	after_validation :geocode


	protected

	def ensure_user_not_has_duplicates
		if Travel.exists?

		end	

	end	



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :database_authenticatable, :confirmable


  has_many :posts, dependent: :destroy
  has_many :photos, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  has_many :travels, dependent: :destroy
  has_many :nextTravels, dependent: :destroy

  acts_as_messageable

  ratyrate_rater

  # in User.rb
  protected
  def confirmation_required?
    false
  end
 
  def mailboxer_name
    self.id
  end
 
  def mailboxer_email(object)
    self.email
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
    	# how to get the number of unread messages for the current user
    	# using mailboxer
    	mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/travels_helper.rb
module TravelsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>








</head>


	<% if user_signed_in? %>

		<body>

			<% if current_user.profile.blank? %>

			<div style="width:600px;margin:0 auto;">

				<p align="center">
					<h3>Aggiorna informazioni profilo per continuare</h3>
				</p>
				<%= render partial: "profiles/form"%>
				<%= link_to "Logout", destroy_user_session_path, method: :delete%>
			</div>

			<% else %>

				<%= render partial: "shared/navbar"%>
				 <div class="container">

				 	<% if notice %>
      					<p class="alert alert-success"><%= notice %></p>
					<% end %>

					<% if alert %>
    					<p class="alert alert-danger"><%= alert %></p>
					<% end %>


					<%= yield %>

				</div>


			<% end %>



	<% else %>

		<%= yield %>




	<% end %>








	</body>

</html>

app/views/shared/_footer.html.erb
<!-- FOOTER -->


    <div style="position : absolute;
	       	color: white;
			font-family:Courier;
    		bottom : 0;
    		left: 0;
    		height : 40px;
            margin-top:20px;
    		
    		width:100%;
    		padding: 10px;
    		border: 0px solid black;
    		">

    		<p align="center">
    	       	Developed by Carmelo Riolo - All Rights Reserved ©<br>
        	</p>

</div>
    

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      
      <!-- LEFT MENU -->

      <div class="navbar-brand">
        <%= link_to '<span class="glyphicon glyphicon-home"></span>'.html_safe, homepage_path(), id: "navbar-brand-item_home" %>
        &nbsp
        <%= link_to '<span class="glyphicon glyphicon-envelope"></span>'.html_safe, mailbox_inbox_path(), id: "navbar-brand-item_home" %>
        &nbsp
        <%= link_to '<span class="glyphicon glyphicon-camera"></span>'.html_safe, photos_path(), id: "navbar-brand-item_home" %>
        &nbsp
        <%= link_to '<span class="glyphicon glyphicon-stats"></span>'.html_safe, analytics_path(), id: "navbar-brand-item_home" %>
        


      </div>



      <!--- SEARCH -->

      <% if user_signed_in? %>
        <form class="navbar-form navbar-left" role="search" action="/search" method="GET">
          <div class="form-group">
            <input type="text" class="form-control-xs" id="search-input" placeholder="Search Post By Location.." name="q" required>
            
          <input class="btn btn-sm btn-primary" type="submit" value="Search" style="height: 25px;"></input>
            
          </button>
          </div>
        </form>


      <% end %>
      
      <!-- -->
        

      
    </div>






    <!-- RIGHT MENU -->


      <ul class="nav navbar-nav navbar-right">
      <%if (user_signed_in?) %>

        
        
        <% if !(current_user.profile == nil) %>
          <%= link_to current_user.profile.nome + " " + current_user.profile.cognome, user_profile_path(id:current_user.id), class: "navbar-brand", id: "navbar-user-link"%>
        <% else %>
          <%= link_to current_user.email, str, class: "navbar-brand", id: "navbar-user-link"%>
        <% end %>  
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-chevron-down white">
          </a>
          <ul class="dropdown-menu" role="menu">
          
            
            <!--  
            <li class="divider"></li>
            -->
                        
            <li>
              <%= link_to "Impostazioni", edit_user_registration_path%>
            </li>
            


              <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete%>
              </li>
          </ul>
        </li>
      
      <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>